<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

$table = $this->tableInfo;

// Set page and window title.
$tableTitle = $table->getTitle();
$pageTitle = $tableTitle . " Table";
$this->headTitle($pageTitle);           // has no effect here? too late?

// Get values from set table for title area and data area.
$tableFootnote = $table->getTableFootnote();
$tableValues = $this->dataToDisplay;    // Set in controller

// Get sequence & table setting name, which indicates the helper script to use.
$helperScriptName = $this->sequenceName;

// Determine instructions and messages specific to this page.
$instructions = "";
$msgs = $this->msgs;                    // Set in controller
$msgs[] = "Found " . count($tableValues) . " entries.";
$errormsgs = $this->errMsgs;            // Set in controller
$errormsgs[] = $this->undefinedFieldsErrorMsg;

?>

<form id="table-view-form" enctype="application/x-www-form-urlencoded"
    action="" method="post">

<!-- Display title bar -->
<div id="titlebar-area">

<!-- Display title and messages -->

<div id="left-column" class="column">  <!-- Contains title block and msgs -->
<?php echo $this->partial("table/_titleblockAndMsgs.phtml",
            array('title'=>$pageTitle, 'description' => "",
                  'footnote'=>$tableFootnote, 'instructions'=>$instructions,
                  'msgs'=>$msgs, 'errormsgs'=>$errormsgs)); ?>
</div>  <!-- End of "left-column" -->

</div>  <!-- End of "titlebar-area" -->

<?php

// Should catch exceptions if no helper and print an error message.

try
{
    echo $this->partial("report/" . $helperScriptName . ".phtml",
        array('visibleFieldInfo' => $table->getVisibleFields(),
              'keyFields' => $table->getPrimaryKeys(),
              'tableValues' => $this->dataToDisplay));
}
catch (Exception $e)
{
    $helperScriptName = "_reportView";
    echo $this->partial("report/" . $helperScriptName . ".phtml",
        array('visibleFieldInfo' => $table->getVisibleFields(),
              'keyFields' => $table->getPrimaryKeys(),
              'tableValues' => $this->dataToDisplay));
    /*
    throw new Exception("Cannot find customized report generator for this " .
        "table setting (trying to find table/$helperScriptName.phtml).");
     */
}

?>

</form>

<?php

?>
