<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

$this->title = "Role Validation";
$this->headTitle($this->title);
?>

<h2>User Role Validation</h2>
<?php if ( count($this->invalid) == 0 ) { ?>
<p>All roles used in the users table have been defined.</p>
<?php
} else
{
    echo "<ul>\n";
    foreach ( $this->invalid as $role )
    {
        echo "<li>Invalid role: $role</li>\n";
    }
    echo "</ul>\n";
}
?>
