<?php
require_once('Michelf/Markdown.php');
use \Michelf\Markdown;

/*
echo "<p>Debugging info is:</p>";
echo "<pre>\n"; print_r($this->activityList); echo "\n</pre>";
echo "<p>activity key: "; print_r($this->activityKey); echo "</p>";
echo "<p>activity type: "; print_r($this->activityType); echo "</p>";
echo "<p>activity: "; print_r($this->activity); echo "</p>";
 */

// Heading may be specified with the activity or may be the
// default: "Choose an activity".
$userSpecifiedHeading = $this->activityTitle;   // set in controller
$heading = $userSpecifiedHeading ? : "Choose an activity:";
?>

<div id='activityPage'>

<?php if ( $heading != "" ) echo "<h1>$heading</h1>" ?>


<form id='activityList' action='' method='post'>
<dl>

<?php if ( $this->message != "" ) echo "$this->message" ?>

<?php
if ( isset($this->activityList) && is_array($this->activityList) )
{
    foreach ( $this->activityList as $key => $activity )
    {
        switch ($activity->getType())
        {
            case Application_Model_ActivitySpec::COMMENT_TYPE:
                    $comment = $this->escape($activity->getComment());
                    $comment = Markdown::defaultTransform($comment);
                    $commentClass = $activity->isInactive()
                        ? "class='disabledComment'" : "class='comment'";
                    echo "<dt $commentClass>";
                    echo $this->partial("activity/_cleanIfSinglePar.phtml",
                            array('content'=>$comment,
                            'includeBreak' => "true"));
                    echo "</dt><dd></dd>\n";
                    break;

            case Application_Model_ActivitySpec::SEPARATOR_TYPE:
                    echo "<dt class='wide'>" . "<hr />" . "</dt><dd></dd>\n";
                    break;

            default:        // SETTING and ACTIVITY_LIST types
                    // Get and format title for button.
                    $title = $this->escape($activity->getTitle());
                    // $title = Markdown::defaultTransform($title);

                    // Get and format description.
                    $desc = $this->escape($activity->getDescription());
                    $desc = Markdown::defaultTransform($desc);

                    // Should button be disabled?
                    $disabledOrNot =
                        $activity->isInactive() ? "disabled" : "";
                    $descDisabledOrNot =
                        $activity->isInactive() ? "class='disabled'" : "";
                    echo "<dt><input type='submit'  name='$key' id='$key' " .
                        "class='button btn' value='$title' $disabledOrNot>" .
                        "</dt>\n";
                    echo "<dd $descDisabledOrNot>";
                    echo $this->partial("activity/_cleanIfSinglePar.phtml",
                            array('content'=>$desc,
                            'includeBreak' => "false"));
                    echo $desc;
                    echo "</dd>\n";
        }
    }
}

?>

</dl>
</form>

</div>
