<?php
$table = $this->tableInfo;

// Set page and window title.
$this->headTitle($this->title);         // Set in controller
$tableTitle = $table->getTitle();
$this->headTitle($tableTitle);

// Get values from set table for title area and data area.
$seqSetting = $this->seqSetting;        // Set in controller
$tableFootnote = $table->getTableFootnote();
$visibleFieldInfo = $table->getVisibleFields();
$keyFields = $table->getPrimaryKeys();
$tableValues = $this->dataToDisplay;    // Set in controller
$highlightEveryN = 5;

// Determine instructions and messages specific to this page.
$instructions = "";
$msgs = $this->msgs;                    // Set in controller
$msgs[] = "Found " . count($tableValues) . " entries.";
$errormsgs = $this->errMsgs;            // Set in controller
$errormsgs[] = $this->undefinedFieldsErrorMsg;

// Construct core parameters to send to all actions.
$commonParams = $this->baseParams;      // Set in controller
$searchParams = $commonParams + array('action'=>'search');
$addParams = $commonParams + array('action'=>'add');
$selectParams = $commonParams + array('action'=>'page-display');
$deleteParams = $commonParams + array('action'=>'delete');
$displayAllParams = $commonParams + array('action' => 'multi-display');
?>

<div id="titlebar-area">

<!-- Display buttons in sidebar -->

<div id="title-sidebar" class="sidebar"> <!-- Contains action buttons -->
    <p><a href="<?php echo $this->url($searchParams, null, true);
        ?>">Search</a></p>
    <p><a href="<?php echo $this->url($addParams, null, true);
        ?>">Add new entry</a></p>
    <?php if ( $this->displayingSubset ) : ?>
    <p><a href="<?php echo $this->url($displayAllParams, null, true);
        ?>">Display all</a></p>
    <?php endif; ?>
</div>  <!-- End of "sidebar" -->

<!-- Display title and messages -->

<div id="left-column" class="column">  <!-- Contains title block and msgs -->
<?php echo $this->partial("table/_titleblockAndMsgs.phtml",
            array('title'=>$tableTitle, 'description' => "",
                  'footnote'=>$tableFootnote, 'instructions'=>$instructions,
                  'msgs'=>$msgs, 'errormsgs'=>$errormsgs)); ?>
</div>  <!-- End of "left-column" -->

</div>  <!-- End of "titlebar-area" -->


<!-- Display records -->

<div id='record-list'>
<table>
<?php
$rowNum = 0;
foreach($tableValues as $recordValues) :
?>

    <!-- Display table entries in rows... -->
    <tr>
    <?php

    // Determine fields to display, whether to highlight, and which 
    // fields to pass as parameters to select and delete requests.
    $rowNum++;
    $rowSpecParams = array();
    $class = "";
    // $class = ($rowNum % $highlightEveryN) ? "" : " class='highlighted'";
    foreach ( $keyFields as $keyFieldName => $ignoredFieldInfo ) :
        $rowSpecParams[$keyFieldName] = $recordValues[$keyFieldName];
    endforeach;
    ?>

    <!-- Display visible field values. -->
    <?php
    foreach($visibleFieldInfo as $fieldName => $field) :
        $title = $field->getFieldFootnote();
        $title = $title ? " title='$title'" : "";
        echo "<td" . $this->escape($class) . $this->escape($title) . ">";
        echo $this->escape($recordValues[$fieldName]) . "</td>";
    endforeach;
    ?>

    <!-- Display select/delete links -->
    <td>
        <a href="<?php echo $this->url(
            $selectParams + $rowSpecParams, null, true); ?>">Select</a>
        <a href="<?php echo $this->url(
            $deleteParams + $rowSpecParams, null, true); ?>">Delete</a>
    </td>
    </tr>

<?php endforeach; ?>

</table>
</div>  <!-- End of "record-list" -->

<?php

?>
