<a name="top" id="top"></a>
<!--
<div id="scrn-read" title="links to aid navigation for screen readers">
    [<a href="#content" accesskey="s">Skip to main content</a>]
</div>
    <h1><span class="appName">Ramp:</span> <span class="appDesc">
        Record and Activity Management Program</span></h1>
-->
<div id="header">
<h1>
<?php
if ( ! empty($this->title) ) : ?>
    <span class="appName"><?php echo $this->title; ?></span><?php
else : ?>
    <span class="appName">Ramp</span><?php
endif; ?><?php
if ( ! empty($this->subtitle) ) :
    ?><span class="appName">:</span>
    <span class="appDesc"><?php echo $this->subtitle; ?></span></h1>
<?php endif; ?>
</div>

