<!--
<a name="top" id="top"></a>
<div id="scrn-read" title="links to aid navigation for screen readers">
    [<a href="#content" accesskey="s">Skip to main content</a>]
</div>
-->

<?php

/* Determine title and subtitle (if any) */
$title = empty($this->title) ? "Ramp" : $this->title;
$subtitle = empty($this->subtitle) ? "" : ": " . $this->subtitle;

/* Determine "Logged in as" message (if any) */
$auth = Zend_Auth::getInstance();
$loggedInMsg = "";
if ( $auth->hasIdentity() )
{
    $user = $auth->getIdentity();
    $loggedInMsg = "Logged in as " . $user->username;
}

?>

<div id="header" class="row">

<?php
echo "<div id='header-left' class='column span10'>\n";
echo "<h1 class='appName'>$title<small>$subtitle</small></h1>\n";
echo "</div>\n<div id='header-right' class='span2'>\n";
echo "<h1 class='loggedInAs pull-right'><small>$loggedInMsg</small></h1>\n";
echo "</div>\n";
?>

</div>

