<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp
 * @copyright  Copyright (c) 2013 Alyce Brady
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

/* This script generates the menu bar for Ramp/Smart pages.
 *
 * Created for use with Twitter-Bootstrap, Ashton Galloway, March 2013
 */

$configs = Ramp_RegistryFacade::getInstance();
$auth = Zend_Auth::getInstance();
$loginURL = $this->url(array('controller'=>'auth', 'action'=>'login'));
$logoutURL = $this->url(array('controller'=>'auth', 'action'=>'logout'));
$changepwURL = $this->url(array('controller'=>'auth',
                    'action'=>'change-password'));
$msgs = array();
if ( $auth->hasIdentity() )
{
    if ( $configs->usingInternalAuthentication() )
    {
        $msgs[] = "<a href='$changepwURL'>Change password</a>";
    }
    $msgs[] = "<a href='$logoutURL'>Log out</a>";
}
else
{
    $msgs[] = "<a href='$loginURL'>Log in</a>";
}

?>

<div id="menu-bar" class="navbar row">
<div class="navbar-inner">

<ul id="main-menu" class="nav">
    <?php foreach($this->container as $page)
    {
        if($page->pages == null)
        {
            $uri = $this->baseUrl($page->uri);
            echo '<li><a href="' . $uri . '">' . $page->label .
                 '</a></li>';
        }
        else
        {
            $uri = $this->baseUrl($page->uri);
            echo '<li class="dropdown">' .
                 '<a class="dropdown-toggle" data-toggle="dropdown" ' .
                 'href="#">' . $page->label . '</a>';
            echo '<ul class="dropdown-menu" role="menu">';
            echo '<li><a href="' . $uri . '">' . $page->label .
                 '</a><hr /></li>';
            foreach($page->pages as $child)
            {
                $uri = $this->baseUrl($child->uri);
                echo '<li class="child"><a href="' . $uri . '">' .
                     $child->label . '</a></li>';
            }
            echo '</ul></li>';
        }
    }
    ?>
</ul>

<ul id="main-menu" class="nav pull-right">
    <?php foreach($msgs as $msg)
    {
        echo "<li>$msg</li>";
    }
    ?>
</ul>

</div>
</div>

