<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle()->prepend('RAMP');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/tableModule.css');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
</head>

<body>
<?php echo $this->partial("_header.phtml", array('title'=>$this->title)); ?>
<?php echo $this->layout()->menu; ?>
<div id="content">
    <?php echo $this->layout()->content; ?>
</div>
<?php echo $this->partial("_footer.phtml"); ?>
</body>

</html>
