<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php if ( isset($this->icon) ) : ?>
        <link rel='icon' href='<?php echo $this->icon; ?>'>
    <?php endif; ?>
</head>

<body>
<?php echo $this->partial("_header.phtml",
        array('title'=>$this->pageTitle, 'subtitle'=>$this->pageSubTitle)); ?>
<?php echo $this->layout()->menu; ?>
<div id="content">
    <?php echo $this->layout()->content; ?>
</div>
<?php echo $this->authDebugging; ?>
<?php echo $this->partial("_footer.phtml"); ?>
</body>

</html>
