<?php
/* This helper script expects an array of button labels.
*/

// Technique for turning button labels into valid name identifiers taken
// from Zend_Form_Element.
$charset = '^a-zA-Z0-9_\x7f-\xff';
?>

<fieldset id="button-list">
<div class="btn-group btn-group-vertical pull-right">

<?php
foreach ( $this->buttonList as $buttonLabel ) :
    $buttonType = ( $buttonLabel == TableController::RESET_BUTTON ) ?
                        "reset" : "submit";
    $buttonLabel = $this->escape($buttonLabel);
    $buttonId = $this->escape(preg_replace('/[' . $charset . ']/', '', 
                                    (string) $buttonLabel));
    echo "<input type='$buttonType' name='submit' id='$buttonId'
            value='$buttonLabel' class='btn' />\n";
endforeach;
?>

</div>
</fieldset>

