<?php
  /* This helper script expects a string in HTML format ('content').
   */

    // If the content is a single paragraph, don't need <p> </p> tags 
    // because the content is already in another block tag (<dt> or <dd>).
    $content = $this->content;
    $paragraphs = explode('<p>', $content);
    if ( count($paragraphs) == 2 )
    {
        // strip off beginning/end paragraph
        $begP = strpos($content, '<p>');
        $endP = strrpos($content, '</p>');
        $lenComment = $endP - ($begP + 3);
        $prefix = $begP == 0 ? "" : substr($content, 0, $begP - 1);
        $content = $lenComment > 0
                    ? substr($content, $begp + 3, $lenComment) : "";
        $content = $prefix . $content .  substr($content, $endP + 4);
    }

    echo $content;
?>
