<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

require_once('Michelf/Markdown.php');
use \Michelf\Markdown;

// Get parameters sent in.
$table = $this->table;

// Get values from set table for data area.
$visibleFieldInfo = $table->getVisibleFields();

?>

<!-- Display column headers -->

<thead>
<tr>
    <?php
    foreach ( $visibleFieldInfo as $fieldName => $field ) :
        $footnote = $this->escape( $field->getFieldFootnote());
        if ( ! empty($footnote) )
        {
            $footnote = Markdown::defaultTransform($footnote);
            $footnote = $this->partial("_cleanIfSinglePar.phtml",
                            array('content'=>$footnote));
        }
        $title = $footnote ? "title='$footnote'" : "";
        echo "<th $title>";
        $colHeading =
            Markdown::defaultTransform($this->escape($field->getLabel()));
        echo $this->partial("_cleanIfSinglePar.phtml",
                array('content'=>$colHeading)) . "</th>\n";
    endforeach;
    if ( $this->includeActions ) :
        echo "<th colspan='3' class='noprint center'> Actions </th>\n";
    endif;
    ?>
</tr>
</thead>

