<?php

/* This helper script expects an external table name, an external table 
 * reference object, and a Zend_Form object containing field elements.
 *
 */

// Establish status codes.
$statusCodes = array(
        // Application_Model_SetTable::UNKNOWN => 'icon-question-sign',
        Application_Model_SetTable::BLANK =>
            array('icon' => 'icon-minus', 'text' => 'Empty'),
        Application_Model_SetTable::PARTIAL =>
            array('icon' => 'icon-adjust',
                  'text' => 'Missing recommended fields'),
        Application_Model_SetTable::GOOD =>
            array('icon' => 'icon-ok',
                  'text' => 'Has all recommended fields')
              /* Other possibilities: 'icon-ok', 'icon-ok-sign' */
    );

// Get the objects passed to this partial helper.
$table = $this->table;
$status = $this->status;

// Create a status indicator for whether all recommended fields have 
// been set for this record in the external table.
$icon = $statusCodes[$status]['icon'];
$text = $statusCodes[$status]['text'];
echo "<i class='$icon statusCode' title='$text'> </i>\n";

?>
