<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

  /* This helper script expects an array with the following:
   *    - a string ('value')
   *    - the keyword for an HTML tag, e.g., 'p' or 'li' ('tag')
   */

$tag = $this->escape($this->tag);

if ( strlen($this->value) > 0 ) :
    echo "<$tag>";
    echo $this->escape($this->value);
    echo "</$tag>";
endif;

?>

