<?php

/* This helper script expects an array containing the set table
 * object and a Zend_Form object containing field elements.
 *
 * Attribution: the structure of rendering label, element, and errors 
 * separately, to allow the insertion of href links, came from:
 * http://monzee.wordpress.com/2009/02/23/decorators-are-hard-lets-go-shopping/
 *
 * Updated for Twitter-Bootstrap, Ashton Galloway, March 2013
 */

$fields = $this->table->getFields();
$form = $this->form;
$fieldElts = $form->getFieldElements();
$searchOpElts = $form->getComparatorElements();
$isSearch = isset($this->search) && $this->search;
$suffix = Application_Form_TableRecordEntry::SEARCH_COMP_SUFFIX;
?>

<?php  /* <div class="control-group row"> */ ?>
<?php foreach ( $fieldElts as $name => $elt ) :
    echo "<div class='control-group'>\n";
    echo "<div id='$name-label' class='control-label'>";
    echo $this->partial("table/_fieldLabel.phtml",
            array('formType'=>$form->getFormType(), 'fields'=>$fields,
                  'fieldName' => $name, 'elt'=>$elt));
    echo "</div>\n";
    echo "<div class='row controls'>\n";
    if ( $isSearch ) :
        $opSearchElt = $searchOpElts[$name];
        echo $opSearchElt->renderElem() . "\n";
    endif;
    echo $elt->renderElem() . "\n";
    echo $elt->renderErrors();
    echo "</div>\n";
    echo "</div>\n";
endforeach; ?>

