<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

$table = $this->tableInfo;                  // Set in controller

// Get relevant information about fields from controller.  Ensure that
// user has ability  to provide any key, necessary fields.
$fields = $table->getFields();
$linkFields = $table->getTableLinkFields();

// Set page and window title.
$action = "Add New Entry";
$tableTitle = $table->getTitle();
$headTitle = $action . " to " . $tableTitle;
$this->headTitle($headTitle);
$titleAndMsgs['title'] = $tableTitle . ": " . $action;

// Determine instructions and messages specific to this page.
$titleAndMsgs['instructions'] = "";
$titleAndMsgs['msgs'] = $this->msgs;        // All msgs are set in controller
$titleAndMsgs['errormsgs'] = $this->errMsgs;
$titleAndMsgs['errormsgs'][] = $this->undefinedFieldsErrorMsg;
$canAddEntries = true;
foreach ( $fields as $field )
{
    if ( $field->valueNecessaryForAdd() && ! $field->isVisible() )
    {
        $titleAndMsgs['errormsgs'][] .=
                    "Error: Cannot add entries to this table without values " .
                    "for " . $this->escape($field->getLabel()) .
                    ", which is a hidden field.";
        $canAddEntries = false;
    }
}

// Get other values from set table for title area.
$titleAndMsgs['description'] = "";
$titleAndMsgs['footnote'] = $table->getTableFootnote();
$titleAndMsgs['footnoteAsTooltip'] = true;

$titleBar['titleAndMsgs'] = $titleAndMsgs;
$buttons['buttonList'] = $this->buttonList; // Set in controller
$buttons['firstButtonIsPrimary'] = true;

$form = $this->dataEntryForm;               // Set in controller

?>

<form id="add-page-form" enctype="application/x-www-form-urlencoded"
    action="" method="post" class="form-horizontal">

<div id="page">

<div id="left-column" class="column span9">

<!-- Display title block and messages -->
<?php echo $this->partial("table/_titleblockAndMsgs.phtml",
                          $titleAndMsgs); ?>

<!-- Display data entry fields (if we have enough information) -->
<?php if ( $canAddEntries ) : ?>
    <div id='record-block' class='add'>
    <?php echo $this->partial("table/_tableEntryForm.phtml",
            array('table'=>$table, 'form' => $this->dataEntryForm)); ?>
    </div>
<?php endif; ?>

</div>  <!-- End of "left-column" -->

<!-- Display buttons in sidebar -->
<div id="button-sidebar" class="span3">
<?php echo $this->partial("table/_buttonList.phtml", $buttons); ?>
</div>  <!-- End of "button-sidebar" -->

</div>  <!-- End of "page" -->

</form>
