<?php 

// Set page and window titles
$table = $this->tableInfo;
$action = "Add New Entry";
$tableTitle = $table->getTitle();
$pageTitle = $tableTitle . ": " . $action;
$headTitle = $action . " to " . $tableTitle;
$this->headTitle($headTitle);

// Get values from set table for title area and data area.
$tableFootnote = $table->getTableFootnote();

// Get relevant information about fields.  Ensure that user has ability 
// to provide any key, necessary fields.
$fields = $table->getFields();
$linkFields = $table->getTableLinkFields();

// Determine instructions and messages specific to this page.
$instructions = "";
$msgs = $this->msgs;                    // Set in controller

$errormsgs = $this->errMsgs;            // Set in controller
$canAddEntries = true;
foreach ( $fields as $field )
{
    if ( $field->valueNecessaryForAdd() && ! $field->isVisible() )
    {
        $errormsgs[] .=
                    "Error: Cannot add entries to this table without values " .
                    "for " . $this->escape($field->getLabel()) .
                    ", which is a hidden field.";
        $canAddEntries = false;
    }
}

$extSearchParams = array('controller' => 'table', 'action' => 'search');
?>

<form id="add-page-form" enctype="application/x-www-form-urlencoded"
    action="" method="post">

<!-- Display title bar -->
<div id="titlebar-area">

<!-- Display buttons in sidebar -->
<?php echo $this->partial("table/_buttonList.phtml",
            array('buttonList' => $this->buttonList)); ?>

<!-- Display title and messages -->
<div id="left-column" class="column">  <!-- Contains title block and msgs -->
<?php echo $this->partial("table/_titleblockAndMsgs.phtml",
            array('title'=>$pageTitle, 'description' => "",
                  'footnote'=>$tableFootnote, 'instructions'=>"",
                  'msgs'=>$msgs, 'errormsgs'=>$errormsgs,
                  'footnoteAsTooltip'=>true)); ?>
</div>  <!-- End of "left-column" -->

</div>  <!-- End of "titlebar-area" -->

<!-- Display data entry fields -->
<?php
// If this table setting provides enough information to support adding 
// new entries to the table, show the form.
if ( $canAddEntries ) :
?>

<div id='record-block' class='add'>

<?php echo $this->partial("table/_tableEntryForm.phtml",
        array('table'=>$table, 'form' => $this->form)); ?>

</div>
<?php endif; ?>

</form>
