<?php

$table = $this->tableInfo;

// Get values from set table for data area.
$seqSetting = $this->seqSetting;        // Set in controller
$addSetting = $this->addSetting;        // Set in controller for getting
                                        // filled-in status information
$visibleFieldInfo = $table->getVisibleFields();
$keyFields = $table->getPrimaryKeys();
$tableValues = $this->dataToDisplay;    // Set in controller
$highlightEveryN = 5;

// Set page and window title.
$tableTitle = $table->getTitle();
$title = $tableTitle . " List";
$this->headTitle($title);
$titleAndMsgs['title'] = $title;

// Determine instructions and messages specific to this page.
$titleAndMsgs['instructions'] = "";
$titleAndMsgs['msgs'] = $this->msgs;        // All msgs are set in controller
$titleAndMsgs['msgs'][] = "Found " . count($tableValues) . " entries.";
$titleAndMsgs['errormsgs'] = $this->errMsgs;
$titleAndMsgs['errormsgs'][] = $this->undefinedFieldsErrorMsg;

// Get other values from set table for title area.
$titleAndMsgs['description'] = "";
$titleAndMsgs['footnote'] = $table->getTableFootnote();
$titleAndMsgs['footnoteAsTooltip'] = false;

$titleBar['titleAndMsgs'] = $titleAndMsgs;
$titleBar['buttonList'] = $this->buttonList;   // Set in controller

// Construct core parameters to send to all actions.
$commonParams = $this->baseParams;      // Set in controller
$selectParams = $commonParams + array('action'=>'record-view');
$deleteParams = $commonParams + array('action'=>'delete');

?>

<div>
<form id="list-view-form" enctype="application/x-www-form-urlencoded"
    action="" method="post">

<!-- Display title bar (title, messages, buttons) -->
<?php echo $this->partial("table/_titleBar.phtml", $titleBar); ?>


<!-- Display records -->

<div id='record-list' class='row'>
<table class='table table-striped table-hover table-condensed'>
<tbody>
<?php
$rowNum = 0;
foreach($tableValues as $recordValues) :
?>

    <!-- Display table entries in rows... -->
    <tr>
    <?php

    // Determine fields to display, whether to highlight, and which 
    // fields to pass as parameters to select and delete requests.
    $rowNum++;
    $rowSpecParams = array();
    $class = "";
    // $class = ($rowNum % $highlightEveryN) ? "" : " class='highlighted'";
    foreach ( $keyFields as $keyFieldName => $ignoredFieldInfo ) :
        $rowSpecParams[$keyFieldName] = $recordValues[$keyFieldName];
    endforeach;
    ?>

    <!-- Display visible field values. -->
    <?php
    foreach($visibleFieldInfo as $fieldName => $field) :
        $colHeading = $field->getLabel();
        $title = $field->getFieldFootnote();
        $title = $title ? "$colHeading: $title" : $colHeading;
        $title = " title='$title'";
        echo "<td" . $this->escape($class) . $this->escape($title) . ">";
        echo $this->escape($recordValues[$fieldName]) . "</td>";
    endforeach;
    ?>

    <!-- Display select/delete links -->
    <td class='completionStatus'>
        <?php
        // Display indication of whether record has all recommended fields.
        $status = $addSetting->getStatusOfRecord($rowSpecParams);
        echo $this->partial("table/_externalRef.phtml",
                            array('table' => $table->getDbTableName(),
                                  'status' => $status));
        ?>
    </td>
    <td class='delete'>
        <a href="<?php echo $this->url(
                        $deleteParams + $rowSpecParams, null, true); ?>"><i
                            class='icon-remove' title='Delete'></i></a>
    </td>
    <td class='select'>
        <a href="<?php echo $this->url(
                        $selectParams + $rowSpecParams, null, true); ?>"><i
                            class='icon-search' title='Select'></i></a>
    <!-- Other possibilities: 'icon-zoom-in', 'icon-list', 'icon-list-alt' -->
    </td>
    </tr>

<?php endforeach; ?>

</tbody>
</table>
</div>  <!-- End of "record-list" -->

</form>
</div>

