<?php

/*  Used in table-view, but not here.
require_once('Michelf/Markdown.php');
use \Michelf\Markdown;
 */

$table = $this->tableInfo;

// Get values from set table for data area.
$tableValues = $this->dataToDisplay;    // Set in controller

// Set page and window title.
$tableTitle = $table->getTitle();
$title = $tableTitle . " List";
$this->headTitle($title);
$titleAndMsgs['title'] = $title;

// Determine instructions and messages specific to this page.
$titleAndMsgs['instructions'] = "";
$titleAndMsgs['msgs'] = $this->msgs;        // All msgs are set in controller
$titleAndMsgs['msgs'][] = "Found " . count($tableValues) . " entries.";
$titleAndMsgs['errormsgs'] = $this->errMsgs;
$titleAndMsgs['errormsgs'][] = $this->undefinedFieldsErrorMsg;

// Get other values from set table for title area.
$titleAndMsgs['description'] = "";
$titleAndMsgs['footnote'] = $table->getTableFootnote();
$titleAndMsgs['footnoteAsTooltip'] = false;

$titleBar['titleAndMsgs'] = $titleAndMsgs;
$titleBar['buttonList'] = $this->buttonList;   // Set in controller

?>

<div>
<form id="list-view-form" enctype="application/x-www-form-urlencoded"
    action="" method="post">

<!-- Display title bar (title, messages, buttons) -->
<?php echo $this->partial("table/_titleBar.phtml", $titleBar); ?>


<!-- Display records -->

<div id='record-list' class='row'>
<table class='table table-striped table-hover table-condensed'>

<?php echo $this->partial("table/_multiRecordDisplay.phtml",
                            array('table' => $table,
                                  'addSetting' => $this->addSetting,
                                  'tableValues' => $tableValues,
                                  'baseParams' => $this->baseParams));
?>

</table>
</div>  <!-- End of "record-list" -->

</form>
</div>

