<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

$table = $this->tableInfo;

// Get values from set table for data area.
$tableValues = $this->dataToDisplay;    // Set in controller

// Set page and window title.
$tableTitle = $table->getTitle();
$title = $tableTitle . " List";
$this->headTitle($title);
$titleAndMsgs['title'] = $title;

// Determine instructions and messages specific to this page.
$titleAndMsgs['instructions'] = "";
$titleAndMsgs['msgs'] = $this->msgs;        // All msgs are set in controller
$titleAndMsgs['msgs'][] = "Found " . count($tableValues) . " entries.";
$titleAndMsgs['errormsgs'] = $this->errMsgs;
$titleAndMsgs['errormsgs'][] = $this->undefinedFieldsErrorMsg;

// Get other values from set table for title area.
$titleAndMsgs['description'] = "";
$titleAndMsgs['footnote'] = $table->getTableFootnote();
$titleAndMsgs['footnoteAsTooltip'] = false;

$titleBar['titleAndMsgs'] = $titleAndMsgs;
$titleBar['buttonList'] = $this->buttonList;   // Set in controller
$titleBar['firstButtonIsPrimary'] = false;

?>

<div>
<form id="list-view-form" enctype="application/x-www-form-urlencoded"
    action="" method="post">

<!-- Display title bar (title, messages, buttons) -->
<?php echo $this->partial("table/_titleBar.phtml", $titleBar); ?>


<!-- Display records -->

<div id='record-list' class='row'>
<table class='table table-striped table-hover table-condensed'>

<?php echo $this->partial("table/_multiRecordDisplay.phtml",
                            array('table' => $table,
                                  'addSetting' => $this->addSetting,
                                  'tableValues' => $tableValues,
                                  'baseParams' => $this->baseParams,
                                  'includeActions' => true));
?>

</table>
</div>  <!-- End of "record-list" -->

</form>
</div>

