<?php
$table = $this->tableInfo;

// Set page and window title.
$this->headTitle($this->title);
$tableTitle = $table->getTitle();
$pageTitle = $tableTitle;
$headTitle = "Record Display for " . $tableTitle;
$this->headTitle($headTitle);

// Get values from set table for title area and data area.
$tableFootnote = $table->getTableFootnote();
$buttonList = $this->buttonList;        // Set in controller
$form = $this->dataEntryForm;           // Set in controller

// Determine instructions and messages specific to this page.
$instructions = "";
$msgs = $this->msgs;                    // Set in controller
$errormsgs = $this->errMsgs;            // Set in controller
$errormsgs[] = $this->undefinedFieldsErrorMsg;  // Set in controller

?>

<!-- Display title bar -->
<div id="titlebar-area">

<!-- Display title and messages -->
<div id="left-column" class="column">  <!-- Contains title block and msgs -->
<?php echo $this->partial("table/_titleblockAndMsgs.phtml",
            array('title'=>$pageTitle, 'description' => "",
                  'footnote'=>$tableFootnote, 'instructions'=>"",
                  'msgs'=>$msgs, 'errormsgs'=>$errormsgs,
                  'footnoteAsTooltip'=>false)); ?>
</div>  <!-- End of "left-column" of title and messages -->

</div>  <!-- End of "titlebar-area" -->


<form id="record-page-form" enctype="application/x-www-form-urlencoded"
    action="" method="post" class="form-horizontal">

<!-- Display buttons in sidebar -->
<?php echo $this->partial("table/_buttonList.phtml",
            array('buttonList' => $buttonList)); ?>


<!-- Display data entry fields -->
<div id='record-block' class='view'>
<?php echo $this->partial("table/_tableEntryForm.phtml",
        array('table' => $table, 'form' => $form)); ?>
</div>

<!-- Display external table references -->
<div id='external-refs' class='view'>
<?php
echo $this->partial("table/_externalRefs.phtml",
        array('table' => $table, 'form' => $form));
?>
</div>

</form>
