<?php

$table = $this->tableInfo;                  // Set in controller

// Set page and window title.
$tableTitle = $table->getTitle();
$headTitle = "View " . $tableTitle . " Record";
$this->headTitle($headTitle);
$titleAndMsgs['title'] = $tableTitle;

// Determine instructions and messages specific to this page.
$titleAndMsgs['instructions'] = "";
$titleAndMsgs['msgs'] = $this->msgs;        // All msgs are set in controller
$titleAndMsgs['errormsgs'] = $this->errMsgs;
$titleAndMsgs['errormsgs'][] = $this->undefinedFieldsErrorMsg;

// Get other values from set table for title area.
$titleAndMsgs['description'] = "";
$titleAndMsgs['footnote'] = $table->getTableFootnote();
$titleAndMsgs['footnoteAsTooltip'] = false;

$titleBar['titleAndMsgs'] = $titleAndMsgs;
$buttons['buttonList'] = $this->buttonList; // Set in controller

// Get values from set table for data area.
$form = $this->dataEntryForm;               // Set in controller

?>

<form id="record-page-form" enctype="application/x-www-form-urlencoded"
    action="" method="post" class="form-horizontal">

<div id="page">

<div id="left-column" class="column span9">

<!-- Display title block and messages -->
<?php echo $this->partial("table/_titleblockAndMsgs.phtml",
                          $titleAndMsgs); ?>

<!-- Display data entry fields -->
<div id='record-block' class='view'>
<?php echo $this->partial("table/_tableEntryForm.phtml",
        array('table' => $table, 'form' => $form)); ?>
</div>

<!-- Display external table references -->
<div id='external-refs' class='view'>
<?php
echo $this->partial("table/_externalRefs.phtml",
        array('table' => $table, 'form' => $form));
?>
</div>

</div>  <!-- End of "left-column" -->

<!-- Display buttons in sidebar -->
<div id="button-sidebar" class="span3">
<?php echo $this->partial("table/_buttonList.phtml", $buttons); ?>
</div>  <!-- End of "button-sidebar" -->

</div>  <!-- End of "page" -->

</form>
