<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

// $table is the original full table setting; just used for title/subtitle.
$table = $this->tableInfo;

// Get values from set table for data area.
$sharedTable = $this->sharedViewSetting;            // Set in controller
// $sharedValues = $this->sharedDataToDisplay;         // Set in controller
$sharedForm = $this->sharedDataEntryForm;           // Set in controller
$differentTable = $this->differentViewSetting;      // Set in controller
$differentValues = $this->differentDataToDisplay;   // Set in controller

// Set page and window title.
$tableTitle = $table->getTitle();
$title = $tableTitle;
$this->headTitle($title);
$titleAndMsgs['title'] = $title;

// Determine instructions and messages specific to this page.
$titleAndMsgs['instructions'] = "";
$titleAndMsgs['msgs'] = $this->msgs;        // All msgs are set in controller
// $titleAndMsgs['msgs'][] = "Found " . count($differentValues) . " entries.";
$titleAndMsgs['errormsgs'] = $this->errMsgs;
$titleAndMsgs['errormsgs'][] = $this->undefinedFieldsErrorMsg;

// Get other values from set table for title area.
$titleAndMsgs['description'] = "";
$titleAndMsgs['footnote'] = $table->getTableFootnote();
$titleAndMsgs['footnoteAsTooltip'] = false;

$titleBar['titleAndMsgs'] = $titleAndMsgs;
$titleBar['buttonList'] = $this->buttonList;        // Set in controller
$titleBar['firstButtonIsPrimary'] = false;

?>

<form id="record-page-form" enctype="application/x-www-form-urlencoded"
    action="" method="post" class="form-horizontal">

<div id="page">

<div id="left-column" class="column span9">

<!-- Display title block and messages -->
<?php echo $this->partial("table/_titleblockAndMsgs.phtml",
                          $titleAndMsgs); ?>

<!-- Display data entry fields -->
<div id='record-block' class='view split-view'>
<?php

echo $this->partial("table/_tableEntryForm.phtml",
    array('table' => $sharedTable, 'form' => $sharedForm));
?>
</div>

</div>  <!-- End of "left-column" -->

<!-- Display buttons in sidebar -->
<div id="button-sidebar" class="span3">
<?php echo $this->partial("table/_buttonList.phtml", $titleBar); ?>
</div>
<!-- End of "button-sidebar" -->

<div id="different-values-view">

<div id='record-split-table' class='row'>
<table class='table table-striped table-hover table-condensed'>

<!-- Display column headers -->

<?php echo $this->partial("table/_colHeadingDisplay.phtml",
            array('table' => $differentTable, 'includeActions' => false));
?>

<!-- Display records -->

<?php echo $this->partial("table/_multiRecordDisplay.phtml",
                            array('table' => $differentTable,
                                  'addSetting' => $this->addSetting,
                                  'tableValues' => $differentValues,
                                  'baseParams' => $this->baseParams,
                                  'includeActions' => false));

?>

</table>
</div>  <!-- End of "record-split-table" -->

</div>  <!-- End of "different-values-view" -->

</form>

</div>  <!-- End of "page" -->

